"""Fix foreign key in Message model

Revision ID: f423f35fd005
Revises: 
Create Date: 2025-02-18 22:14:57.368889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f423f35fd005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('messages_receiver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('receiver_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_receiver_id_fkey', 'users', ['receiver_id'], ['id'])
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
